### ISSUE TITLE
你好，可以使用单GPU训练吗

### ISSUE THREAD

**Issue by zhangshilong2000** [StevenLauHKHK/Large-Separable-Kernel-Attention#1]

**Comment by StevenLauHKHK** [comment]
Yes. You can use single GPU to train it. But you need to set the number of GPU to 1 in the training bash script. 
 
CUDA_VISIBLE_DEVICES=0 bash distributed_train.sh **1** /path/to/imagenet \
	  --model $MODEL -b 128 --lr 1e-3 --drop-path $DROP_PATH --k_size kernel_size \
	  --log_name log_file_name

**Comment by zhangshilong2000** [comment]
感谢您的及时回复！
&nbsp;


张世龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月9日(星期二) 中午11:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [StevenLauHKHK/Large-Separable-Kernel-Attention] 你好，可以使用单GPU训练吗 (Issue #1)






是的。你可以使用单个GPU来训练它。但您需要在训练bash脚本中将GPU的数量设置为1。

CUDA _ VISIVAL _ DEVICES = 0 bash 分布式_train.sh1/路径/到/图像网络
--模型$MODEL-B128-LR 1e-3-放置路径$DROP_PATH-k_size内核_size
--log_name日志文件名

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
***@***.***和&gt;
